#!/usr/bin/env node
import { mkdirSync, writeFileSync, readFileSync, existsSync, copyFileSync } from "node:fs";
import { resolve, dirname } from "node:path";

function readJson(path) {
  if (!existsSync(path)) return null;
  try {
    return JSON.parse(readFileSync(path, "utf-8"));
  } catch {
    return null;
  }
}

function write(path, content) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

function pascalCase(text) {
  return text
    .replace(/[^A-Za-z0-9]+/g, " ")
    .trim()
    .split(/\s+/)
    .map((w) => (w[0]?.toUpperCase() ?? "") + w.slice(1))
    .join("");
}

function rootPackageJson() {
  return JSON.stringify(
    {
      name: "chimera-clone",
      version: "0.1.0",
      private: true,
      description: "Reconstructed application — generated by chimera-dev/app-reconstructor",
      scripts: {
        dev: "pnpm -r --parallel run dev",
        build: "pnpm -r run build",
        test: "pnpm -r run test",
      },
      engines: { node: ">=18.0.0" },
    },
    null,
    2
  ) + "\n";
}

function workspaceYaml() {
  return `packages:\n  - "apps/*"\n  - "packages/*"\n`;
}

function tsconfigBase() {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        module: "ESNext",
        moduleResolution: "Bundler",
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        resolveJsonModule: true,
        jsx: "react-jsx",
      },
    },
    null,
    2
  ) + "\n";
}

function gitignore() {
  return `node_modules/\ndist/\n.env\n.env.local\n*.log\n.DS_Store\n`;
}

function rootReadme() {
  return `# chimera-clone\n\nReconstructed application generated by [chimera-dev](https://github.com/noahweiss3/chimera-dev).\n\n## Getting started\n\n\`\`\`bash\npnpm install\ncp .env.example .env  # set DATABASE_URL\npnpm --filter @chimera-clone/api db:push\npnpm dev\n\`\`\`\n\nThe LLM scaffolded this codebase from \`.chimera/\`. Route handlers, page components, and the shared schema barrel were filled in by hand after \`scaffold.mjs\`. See \`docs/scaffold-todos.md\` if it exists.\n`;
}

function apiPackageJson() {
  return JSON.stringify(
    {
      name: "@chimera-clone/api",
      version: "0.1.0",
      private: true,
      type: "module",
      scripts: {
        dev: "tsx watch src/index.ts",
        build: "tsc -p tsconfig.json",
        "db:push": "drizzle-kit push",
        "db:studio": "drizzle-kit studio",
      },
      dependencies: {
        "drizzle-orm": "^0.31.0",
        express: "^4.19.0",
        pg: "^8.12.0",
        zod: "^3.23.0",
        "@chimera-clone/shared": "workspace:*",
      },
      devDependencies: {
        "@types/express": "^4.17.0",
        "@types/node": "^20.0.0",
        "@types/pg": "^8.11.0",
        "drizzle-kit": "^0.22.0",
        tsx: "^4.0.0",
        typescript: "^5.4.0",
      },
    },
    null,
    2
  ) + "\n";
}

function apiTsconfig() {
  return JSON.stringify(
    {
      extends: "../../tsconfig.base.json",
      compilerOptions: {
        outDir: "dist",
        rootDir: "src",
      },
      include: ["src/**/*"],
    },
    null,
    2
  ) + "\n";
}

function drizzleConfig() {
  return `import type { Config } from "drizzle-kit";

export default {
  schema: "./src/db/schema.ts",
  out: "./drizzle",
  dialect: "postgresql",
  dbCredentials: {
    url: process.env.DATABASE_URL ?? "",
  },
} satisfies Config;
`;
}

function apiIndex(entities) {
  const importLines = entities
    .map((e) => `import ${e.table}Routes from "./routes/${e.table}.js";`)
    .join("\n");
  const useLines = entities
    .map((e) => `app.use("/api/${e.table}", ${e.table}Routes);`)
    .join("\n");
  return `import express from "express";
${importLines}

const app = express();
app.use(express.json());

${useLines}

app.get("/health", (_req, res) => res.json({ status: "ok" }));

const port = Number(process.env.API_PORT ?? 4000);
app.listen(port, () => console.log(\`api listening on \${port}\`));
`;
}

function dbClient() {
  return `import { drizzle } from "drizzle-orm/node-postgres";
import pg from "pg";
import * as schema from "./schema.js";

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });

export const db = drizzle(pool, { schema });
export { schema };
`;
}

function routeStub(entity) {
  return `// TODO(chimera): implement CRUD handlers for the ${entity.name} entity.
// Use db.query.${entity.table}.* for reads and db.insert/update/delete for writes.
// Reference: .chimera/api-spec/openapi.json for the contract and
// .chimera/model/entities.json for field-level info.

import { Router } from "express";
import { db, schema } from "../db/client.js";

const router = Router();

router.get("/", async (_req, res) => {
  const rows = await db.select().from(schema.${entity.table});
  res.json(rows);
});

// TODO(chimera): GET /:id, POST /, PATCH /:id, DELETE /:id

export default router;
`;
}

function webPackageJson() {
  return JSON.stringify(
    {
      name: "@chimera-clone/web",
      version: "0.1.0",
      private: true,
      type: "module",
      scripts: {
        dev: "vite",
        build: "tsc -p tsconfig.json && vite build",
        preview: "vite preview",
      },
      dependencies: {
        react: "^19.0.0",
        "react-dom": "^19.0.0",
        "react-router-dom": "^6.26.0",
        "@chimera-clone/shared": "workspace:*",
      },
      devDependencies: {
        "@types/react": "^19.0.0",
        "@types/react-dom": "^19.0.0",
        "@vitejs/plugin-react": "^4.3.0",
        typescript: "^5.4.0",
        vite: "^5.4.0",
      },
    },
    null,
    2
  ) + "\n";
}

function webTsconfig() {
  return JSON.stringify(
    {
      extends: "../../tsconfig.base.json",
      compilerOptions: {
        outDir: "dist",
        rootDir: "src",
        jsx: "react-jsx",
      },
      include: ["src/**/*"],
    },
    null,
    2
  ) + "\n";
}

function viteConfig() {
  return `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  server: {
    proxy: {
      "/api": "http://localhost:4000",
    },
  },
});
`;
}

function indexHtml() {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>chimera-clone</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;
}

function mainTsx() {
  return `import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import App from "./App.js";

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </StrictMode>
);
`;
}

function appTsx(screens) {
  if (screens.length === 0) {
    return `// TODO(chimera): No screens detected. Add routes by hand.\nexport default function App() { return <div>chimera-clone</div>; }\n`;
  }
  const imports = screens
    .map((s) => {
      const name = pascalCase(s.name);
      return `import ${name} from "./pages/${name}.js";`;
    })
    .join("\n");
  const routes = screens
    .map((s) => {
      const name = pascalCase(s.name);
      return `        <Route path="${s.url}" element={<${name} />} />`;
    })
    .join("\n");
  return `import { Routes, Route } from "react-router-dom";
${imports}

export default function App() {
  return (
    <main>
      <Routes>
${routes}
      </Routes>
    </main>
  );
}
`;
}

function apiClientStub() {
  return `// TODO(chimera): generate typed fetch functions per endpoint.
// Reference: .chimera/api-spec/client.mjs and .chimera/api-spec/openapi.json.

const BASE_URL = "/api";

export async function apiFetch<T>(path: string, init?: RequestInit): Promise<T> {
  const res = await fetch(\`\${BASE_URL}\${path}\`, init);
  if (!res.ok) throw new Error(\`\${res.status} \${res.statusText}\`);
  return res.json() as Promise<T>;
}
`;
}

function pageStub(screen) {
  const name = pascalCase(screen.name);
  const deps = (screen.data_dependencies ?? [])
    .map((d) => `//   - ${d.endpoint}  (${d.purpose}, on_load=${d.on_load})`)
    .join("\n");
  const actions = (screen.actions ?? [])
    .map((a) => `//   - ${a.trigger}${a.endpoint ? ` -> ${a.endpoint}` : ""}${a.navigates_to ? ` -> screen ${a.navigates_to}` : ""}`)
    .join("\n");
  return `// TODO(chimera): implement the ${name} (${screen.type}) screen.
//
// Data dependencies (load on mount):
${deps || "//   (none)"}
//
// Actions:
${actions || "//   (none)"}
//
// Reference: .chimera/func-map/screens.json (id="${screen.id}") and
// the screenshot at .chimera/pages/${screen.id}/screenshot.png.

export default function ${name}() {
  return (
    <section>
      <h1>${screen.name}</h1>
      <p>TODO: implement this ${screen.type} screen.</p>
    </section>
  );
}
`;
}

function sharedPackageJson() {
  return JSON.stringify(
    {
      name: "@chimera-clone/shared",
      version: "0.1.0",
      private: true,
      type: "module",
      main: "src/schemas.ts",
      dependencies: {
        zod: "^3.23.0",
      },
    },
    null,
    2
  ) + "\n";
}

function sharedTsconfig() {
  return JSON.stringify(
    {
      extends: "../../tsconfig.base.json",
      compilerOptions: { outDir: "dist", rootDir: "src" },
      include: ["src/**/*"],
    },
    null,
    2
  ) + "\n";
}

function sharedSchemasStub() {
  return `// TODO(chimera): generate Zod schemas for each entity in .chimera/model/entities.json.
//
// Convention: \`export const projectSchema = z.object({ … })\` then
// \`export type Project = z.infer<typeof projectSchema>\`.

import { z } from "zod";

export const placeholderSchema = z.object({}).passthrough();
`;
}

export function scaffold({ chimeraDir, outDir, force = false }) {
  const entitiesPath = resolve(chimeraDir, "model/entities.json");
  const entitiesDoc = readJson(entitiesPath);
  if (!entitiesDoc?.entities) {
    return {
      status: "failed",
      error: "model/entities.json missing. Run model-inferrer first.",
    };
  }
  const entities = entitiesDoc.entities;

  const screensDoc = readJson(resolve(chimeraDir, "func-map/screens.json"));
  const screens = screensDoc?.screens ?? [];

  if (existsSync(outDir) && !force) {
    return {
      status: "aborted",
      reason: `${outDir} already exists. Pass force=true to overwrite.`,
    };
  }

  mkdirSync(outDir, { recursive: true });

  write(resolve(outDir, "package.json"), rootPackageJson());
  write(resolve(outDir, "pnpm-workspace.yaml"), workspaceYaml());
  write(resolve(outDir, "tsconfig.base.json"), tsconfigBase());
  write(resolve(outDir, ".gitignore"), gitignore());
  write(resolve(outDir, "README.md"), rootReadme());

  write(resolve(outDir, "apps/api/package.json"), apiPackageJson());
  write(resolve(outDir, "apps/api/tsconfig.json"), apiTsconfig());
  write(resolve(outDir, "apps/api/drizzle.config.ts"), drizzleConfig());
  write(resolve(outDir, "apps/api/src/index.ts"), apiIndex(entities));
  write(resolve(outDir, "apps/api/src/db/client.ts"), dbClient());

  const schemaSrc = resolve(chimeraDir, "model/schema.ts");
  if (existsSync(schemaSrc)) {
    mkdirSync(resolve(outDir, "apps/api/src/db"), { recursive: true });
    copyFileSync(schemaSrc, resolve(outDir, "apps/api/src/db/schema.ts"));
  } else {
    write(
      resolve(outDir, "apps/api/src/db/schema.ts"),
      `// TODO(chimera): model-inferrer did not produce schema.ts. Reconstruct it from .chimera/model/entities.json.\n`
    );
  }

  for (const entity of entities) {
    write(
      resolve(outDir, `apps/api/src/routes/${entity.table}.ts`),
      routeStub(entity)
    );
  }

  write(resolve(outDir, "apps/web/package.json"), webPackageJson());
  write(resolve(outDir, "apps/web/tsconfig.json"), webTsconfig());
  write(resolve(outDir, "apps/web/vite.config.ts"), viteConfig());
  write(resolve(outDir, "apps/web/index.html"), indexHtml());
  write(resolve(outDir, "apps/web/src/main.tsx"), mainTsx());
  write(resolve(outDir, "apps/web/src/App.tsx"), appTsx(screens));
  write(resolve(outDir, "apps/web/src/lib/api.ts"), apiClientStub());

  for (const screen of screens) {
    const name = pascalCase(screen.name);
    write(resolve(outDir, `apps/web/src/pages/${name}.tsx`), pageStub(screen));
  }

  write(resolve(outDir, "packages/shared/package.json"), sharedPackageJson());
  write(resolve(outDir, "packages/shared/tsconfig.json"), sharedTsconfig());
  write(resolve(outDir, "packages/shared/src/schemas.ts"), sharedSchemasStub());

  const llmTodos = [
    "Fill in CRUD handlers in apps/api/src/routes/<entity>.ts using OpenAPI spec + Drizzle schema",
    "Implement page components in apps/web/src/pages/<Screen>.tsx",
    "Generate typed fetch client in apps/web/src/lib/api.ts from .chimera/api-spec/openapi.json",
    "Generate Zod schemas in packages/shared/src/schemas.ts from .chimera/model/entities.json",
  ];

  return {
    status: "done",
    entities_scaffolded: entities.length,
    screens_scaffolded: screens.length,
    files_written: 14 + entities.length + screens.length,
    llm_todos: llmTodos,
    output_dir: outDir,
  };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const chimeraDir = resolve(process.cwd(), ".chimera");
  const outDir = resolve(process.cwd(), "chimera-clone");
  const force = process.argv.includes("--force");
  if (!existsSync(chimeraDir)) {
    console.error(JSON.stringify({ error: "No .chimera/ directory in cwd." }));
    process.exit(1);
  }
  console.log(JSON.stringify(scaffold({ chimeraDir, outDir, force }), null, 2));
}
