import { pluralize } from "./pluralize.mjs";

const DRIZZLE_TYPE_MAP = {
  uuid: "uuid",
  text: "text",
  integer: "integer",
  doublePrecision: "doublePrecision",
  boolean: "boolean",
  timestamp: "timestamp",
  array: "text",
  object: "jsonb",
};

function camelCaseColumn(snake) {
  return snake.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());
}

function importedTypes(entities) {
  const set = new Set();
  for (const entity of entities) {
    for (const f of entity.fields) {
      set.add(DRIZZLE_TYPE_MAP[f.type] ?? "text");
    }
  }
  return [...set].sort();
}

function emitField(field) {
  const drizzleType = DRIZZLE_TYPE_MAP[field.type] ?? "text";
  const colName = camelCaseColumn(field.name);
  let line = `  ${colName}: ${drizzleType}(${JSON.stringify(field.name)})`;

  if (field.primary_key && drizzleType === "uuid") {
    line += `.primaryKey().defaultRandom()`;
  } else if (field.primary_key) {
    line += `.primaryKey()`;
  }
  if (field.foreign_key) {
    const [table, column] = field.foreign_key.split(".");
    line += `.references(() => ${table}.${camelCaseColumn(column)})`;
  }
  if (drizzleType === "timestamp" && field.name.endsWith("_at")) {
    line += `.defaultNow()`;
  }
  if (field.required && !field.primary_key) {
    line += `.notNull()`;
  }
  if (field.enum && Array.isArray(field.enum)) {
    // Drizzle doesn't have inline enum literals; comment for the user
    line += ` /* enum: ${field.enum.map((v) => JSON.stringify(v)).join(", ")} */`;
  }
  return line + ",";
}

function emitTable(entity) {
  const lines = entity.fields.map(emitField).join("\n");
  return `export const ${entity.table} = pgTable(${JSON.stringify(entity.table)}, {\n${lines}\n});`;
}

function emitRelations(entity, byName) {
  const ones = entity.relationships.filter((r) => r.type === "belongs_to");
  const manys = entity.relationships.filter((r) => r.type === "has_many");
  if (ones.length === 0 && manys.length === 0) return "";

  const usesOne = ones.length > 0;
  const usesMany = manys.length > 0;
  const helpers = [usesOne ? "one" : null, usesMany ? "many" : null].filter(Boolean).join(", ");

  const entries = [];
  for (const r of ones) {
    const target = byName.get(r.entity);
    if (!target) continue;
    const fkCol = camelCaseColumn(r.foreign_key);
    const propName = camelCaseColumn(r.entity.toLowerCase());
    entries.push(`  ${propName}: one(${target.table}, { fields: [${entity.table}.${fkCol}], references: [${target.table}.id] })`);
  }
  for (const r of manys) {
    const target = byName.get(r.entity);
    if (!target) continue;
    entries.push(`  ${target.table}: many(${target.table})`);
  }

  if (entries.length === 0) return "";

  return `export const ${entity.table}Relations = relations(${entity.table}, ({ ${helpers} }) => ({\n${entries.join(",\n")},\n}));`;
}

export function buildDrizzleSchema(entities) {
  const typeImports = importedTypes(entities);
  const byName = new Map(entities.map((e) => [e.name, e]));

  const lines = [
    `// Auto-generated by chimera-dev/model-inferrer.`,
    `import { pgTable, ${typeImports.join(", ")} } from "drizzle-orm/pg-core";`,
    `import { relations } from "drizzle-orm";`,
    ``,
  ];

  for (const entity of entities) {
    lines.push(emitTable(entity));
    lines.push("");
  }
  for (const entity of entities) {
    const rel = emitRelations(entity, byName);
    if (rel) {
      lines.push(rel);
      lines.push("");
    }
  }

  return lines.join("\n");
}
