function capitalize(s) {
  return s ? s[0].toUpperCase() + s.slice(1).toLowerCase() : "";
}

export function functionNameFor(method, template) {
  let name = method.toLowerCase();
  const segments = template.split("/").filter(Boolean);
  for (const seg of segments) {
    const paramMatch = seg.match(/^\{(.+)\}$/);
    if (paramMatch) {
      name += "By" + capitalize(paramMatch[1]);
    } else {
      const clean = seg.replace(/[^A-Za-z0-9]+/g, " ").trim();
      for (const word of clean.split(/\s+/).filter(Boolean)) {
        name += capitalize(word);
      }
    }
  }
  return name;
}

function extractParamNames(template) {
  const names = [];
  const re = /\{([^}]+)\}/g;
  let m;
  while ((m = re.exec(template)) !== null) names.push(m[1]);
  return names;
}

function header() {
  return `// Auto-generated by chimera-dev/api-mapper. Do not edit by hand.

const env = (typeof process !== "undefined" && process.env) ? process.env : {};

function buildUrl(baseUrl, path, params, query) {
  let p = path;
  for (const [k, v] of Object.entries(params ?? {})) {
    p = p.replace(\`{\${k}}\`, encodeURIComponent(String(v)));
  }
  const url = new URL(p, baseUrl);
  if (query) {
    for (const [k, v] of Object.entries(query)) {
      if (v === undefined || v === null) continue;
      url.searchParams.set(k, String(v));
    }
  }
  return url.toString();
}

async function request(method, path, params, options = {}) {
  const baseUrl = options.baseUrl ?? env.CHIMERA_BASE_URL ?? "%BASE_URL%";
  const headers = { Accept: "application/json", ...(options.headers ?? {}) };
  %AUTH_INJECT%
  const init = { method, headers };
  if (options.body !== undefined) {
    headers["Content-Type"] = headers["Content-Type"] ?? "application/json";
    init.body = typeof options.body === "string" ? options.body : JSON.stringify(options.body);
  }
  const res = await fetch(buildUrl(baseUrl, path, params, options.query), init);
  const ct = res.headers.get("content-type") ?? "";
  const body = ct.includes("application/json") ? await res.json() : await res.text();
  return { status: res.status, headers: Object.fromEntries(res.headers.entries()), body };
}
`;
}

function authInjection(auth) {
  if (!auth) return "";
  if (auth.type === "bearer") {
    const scheme = auth.scheme ?? "Bearer";
    return `const token = options.token ?? env.CHIMERA_TOKEN; if (token) headers.Authorization = \`${scheme} \${token}\`;`;
  }
  if (auth.type === "api-key") {
    return `const apiKey = options.apiKey ?? env.CHIMERA_API_KEY; if (apiKey) headers[${JSON.stringify(auth.header)}] = apiKey;`;
  }
  if (auth.type === "cookie") {
    return `if (options.cookie) headers.Cookie = options.cookie;`;
  }
  return "";
}

export function buildClient({ endpoints, auth, baseUrl }) {
  let src = header()
    .replace("%BASE_URL%", baseUrl ?? "")
    .replace("%AUTH_INJECT%", authInjection(auth));

  for (const ep of endpoints) {
    if (ep.method === "OPTIONS") continue;
    const fnName = functionNameFor(ep.method, ep.path_template);
    const paramNames = extractParamNames(ep.path_template);
    const args = [...paramNames, "options"].join(", ");
    const paramsObj = paramNames.length
      ? `{ ${paramNames.map((n, i) => `${n}: ${n}`).join(", ")} }`
      : "{}";
    src += `\nexport async function ${fnName}(${args}) {\n  return request(${JSON.stringify(ep.method)}, ${JSON.stringify(ep.path_template)}, ${paramsObj}, options);\n}\n`;
  }

  return src;
}
